name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.12']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        curl -sSL https://pdm-project.org/install-pdm.py | python3 -
        pdm install -dG:all

    - name: Start Milvus
      run: |
        docker compose up -d
        sleep 60  # Wait for Milvus to start
        docker compose ps -a

    - name: Run Test
      run: |
         pdm run pytest -v tests

    - name: Stop Milvus
      if: always()
      run: docker compose down
